stages:
  - prepare
  - build
  - deploy
  - destroy

prepare_job:
  stage: prepare
  tags:
    - shell
  trigger: 
    - project: https://mygta.com:4443/alinuxien/php-mysql-from-dockerfile-to-k8s
    - branch: master
    - job: prepare_job
  artifacts:
    paths: 
      - ./secret-mysql.yaml
 
build_php_job:
  stage: build
  tags:
    - shell
  trigger: 
    - project: https://mygta.com:4443/alinuxien/php-mysql-from-dockerfile-to-k8s
    - branch: master
    - job: build_php_job
 
build_mysql_job:
  stage: build
  tags:
    - shell
  trigger: 
    - project: https://mygta.com:4443/alinuxien/php-mysql-from-dockerfile-to-k8s
    - branch: master
    - job: build_mysql_job

deploy_job:
  stage: deploy 
  tags:
    - shell
  trigger: 
    - project: https://mygta.com:4443/alinuxien/php-mysql-from-dockerfile-to-k8s
    - branch: master
    - job: deploy_job
  allow_failure: true
  artifacts:
    paths: 
      - ./php.yaml
      - ./mysql.yaml
  environment:
    name: php_mysql_in_kube_pods
    url: http://localhost:30000/
  only:
    - master

destroy_job:
  stage: destroy 
  tags:
    - shell
  trigger: 
    - project: https://mygta.com:4443/alinuxien/php-mysql-from-dockerfile-to-k8s
    - branch: master
    - job: deploy_job
  when: manual
