stages:
  - build
  - deploy

variables:
  DEV_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DEV_REGISTRY: $CI_REGISTRY 

build_php_job:
  stage: build
  tags:
    - shell
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DEV_REGISTRY
  script:
    - docker build -t $(echo ${DEV_IMAGE_TAG}) -f Dockerfile .
    - docker push $(echo ${DEV_IMAGE_TAG})

deploy_job:
  stage: deploy
  trigger:
    project: service-on-demand/service-on-demand
    branch: master
    strategy: depend
